/**
 * Commandes palette des fenêtres dont le store UI vit dans le fichier composant
 * (CORR, MAP, TERM, OMON, RATE, COT, SEAG, VOL, FUND, BRIEF, STBL, SQZ, CBPREM).
 *
 * Pilotage via `windowManagerStore` uniquement — **aucune** import des composants
 * lourds — pour permettre le code-splitting (React.lazy) des fenêtres dans App.tsx
 * sans tirer le graphe de dépendances chart/canvas au démarrage.
 *
 * Les fenêtres dont le store est déjà dans `store/*.ts` (ECO, NEWS, DOM…) gardent
 * leurs commandes exportées depuis ces modules.
 */
import type { Commande } from "./registry";
import { windowManagerStore } from "../store/windowManager";

/** Bascule d’ouverture d’une fenêtre du registre Launchpad. */
function basculer(id: string): () => void {
  return () => windowManagerStore.getState().toggleWindow(id);
}

/** Commandes panneau pilotées par le gestionnaire de fenêtres. */
export const windowPanelCommands: Commande[] = [
  {
    id: "panneau:corr",
    mnemonique: "CORR",
    libelle: "Corrélations",
    categorie: "panneau",
    motsCles: ["correlation", "corr", "pearson", "spearman", "matrice", "diversification", "hedge"],
    apercu: "Ouvre / ferme la matrice de corrélation",
    action: basculer("corr"),
  },
  {
    id: "panneau:vue-marche",
    mnemonique: "MAP",
    libelle: "Vue marché (treemap)",
    categorie: "panneau",
    motsCles: ["vue marche", "market map", "treemap", "heatmap", "carte", "secteurs", "capitalisation", "imap"],
    apercu: "Ouvre / ferme la treemap de capitalisation du marché",
    action: basculer("marketMap"),
  },
  {
    id: "panneau:vue-marche-imap",
    mnemonique: "IMAP",
    libelle: "Vue marché (treemap)",
    categorie: "panneau",
    motsCles: ["vue marche", "market map", "treemap", "heatmap", "alias map"],
    apercu: "Alias de MAP — ouvre / ferme la treemap de capitalisation du marché",
    action: basculer("marketMap"),
  },
  {
    id: "panneau:term-structure",
    mnemonique: "TERM",
    libelle: "Structure par terme (basis)",
    categorie: "panneau",
    motsCles: [
      "term structure",
      "structure par terme",
      "basis",
      "contango",
      "backwardation",
      "courbe",
      "futures",
      "deribit",
      "coin-m",
    ],
    apercu: "Ouvre / ferme la courbe de basis annualisé BTC + ETH",
    action: basculer("termStructure"),
  },
  {
    id: "panneau:options",
    mnemonique: "OMON",
    libelle: "Options (smile IV, max pain, GEX/DEX)",
    categorie: "panneau",
    motsCles: [
      "options",
      "omon",
      "smile",
      "iv",
      "volatilite implicite",
      "max pain",
      "put call ratio",
      "dvol",
      "deribit",
      "gex",
      "dex",
      "gamma exposure",
      "delta exposure",
      "cboe",
      "spx",
      "ndx",
      "vix",
    ],
    apercu: "Ouvre / ferme le moniteur d'options (smile, GEX/DEX crypto & actions)",
    action: basculer("options"),
  },
  {
    id: "panneau:macroRates",
    mnemonique: "RATE",
    libelle: "Taux & Réserves souveraines",
    categorie: "panneau",
    motsCles: [
      "taux",
      "rendements",
      "obligations",
      "souverain",
      "treasury",
      "bund",
      "banque centrale",
      "fed",
      "bce",
      "ecb",
      "or",
      "gold",
      "reserves",
      "2s10s",
    ],
    apercu: "Ouvre / ferme les taux souverains, directeurs et réserves d'or",
    action: basculer("macroRates"),
  },
  {
    id: "panneau:cot",
    mnemonique: "COT",
    libelle: "Rapport COT (CFTC)",
    categorie: "panneau",
    motsCles: [
      "cot",
      "commitments of traders",
      "cftc",
      "positionnement",
      "net speculatif",
      "non commercial",
      "futures",
      "sentiment",
    ],
    apercu: "Ouvre / ferme le résumé du rapport COT (CFTC)",
    action: basculer("cot"),
  },
  {
    id: "panneau:seasonality",
    mnemonique: "SEAG",
    libelle: "Saisonnalité",
    categorie: "panneau",
    motsCles: ["saisonnalité", "seasonality", "heatmap", "mensuel", "seag"],
    apercu: "Ouvre / ferme la heatmap de saisonnalité du symbole courant",
    action: basculer("seasonality"),
  },
  {
    id: "panneau:vol",
    mnemonique: "VOL",
    libelle: "Volatilité (cône RV, VRP)",
    categorie: "panneau",
    motsCles: ["volatilité", "volatility", "cône", "cone", "rv", "dvol", "vrp", "vol"],
    apercu: "Ouvre / ferme le cône de volatilité réalisée et la comparaison RV/DVOL",
    action: basculer("vol"),
  },
  {
    id: "panneau:fund",
    mnemonique: "FUND",
    libelle: "Fiche société (FUND)",
    categorie: "panneau",
    motsCles: [
      "fondamentaux",
      "societe",
      "action",
      "equity",
      "profil",
      "earnings",
      "resultats",
      "sec",
      "edgar",
      "finnhub",
      "insider",
      "ticker",
    ],
    apercu: "Ouvre / ferme la fiche société (SEC EDGAR + Finnhub)",
    action: basculer("fund"),
  },
  {
    id: "panneau:brief",
    mnemonique: "BRIEF",
    libelle: "Point marché (BRIEF)",
    categorie: "panneau",
    motsCles: ["brief", "point marché", "snapshot", "matin", "morning", "overnight", "résumé", "ouverture"],
    apercu: "Ouvre / ferme le snapshot marché matinal",
    action: basculer("brief"),
  },
  {
    id: "panneau:stablecoins",
    mnemonique: "STBL",
    libelle: "Stablecoins (supply, dominance, pegs)",
    categorie: "panneau",
    motsCles: [
      "stablecoins",
      "stable",
      "usdt",
      "usdc",
      "dai",
      "tether",
      "circle",
      "impression",
      "mint",
      "burn",
      "dominance",
      "peg",
      "depeg",
      "supply",
    ],
    apercu: "Ouvre / ferme l'analyse des stablecoins (DefiLlama)",
    action: basculer("stablecoins"),
  },
  {
    id: "panneau:squeeze",
    mnemonique: "SQZ",
    libelle: "Radar squeeze",
    categorie: "panneau",
    motsCles: [
      "squeeze",
      "radar",
      "funding",
      "oi",
      "open interest",
      "delta oi",
      "quadrant",
      "long squeeze",
      "short squeeze",
      "crowded",
      "sqz",
    ],
    apercu: "Ouvre / ferme le radar de squeeze (funding × ΔOI par quadrant)",
    action: basculer("squeeze"),
  },
  {
    id: "panneau:cbprem",
    mnemonique: "CBPREM",
    libelle: "Coinbase premium",
    categorie: "panneau",
    motsCles: [
      "cbprem",
      "coinbase premium",
      "premium",
      "coinbase",
      "binance",
      "spot",
      "gap",
      "demande institutionnelle",
      "arbitrage",
    ],
    apercu: "Ouvre / ferme le premium spot Coinbase vs Binance (demande institutionnelle US)",
    action: basculer("cbprem"),
  },
  {
    id: "panneau:netliq",
    mnemonique: "NETLIQ",
    libelle: "Liquidité nette Fed",
    categorie: "panneau",
    motsCles: [
      "netliq",
      "liquidite nette",
      "liquidity",
      "fed",
      "walcl",
      "tga",
      "rrp",
      "reverse repo",
      "bilan fed",
      "reserves",
      "macro",
    ],
    apercu: "Ouvre / ferme la liquidité nette de la Fed (WALCL − TGA − RRP sur 2 ans)",
    action: basculer("netliq"),
  },
  {
    id: "panneau:data",
    mnemonique: "DATA",
    libelle: "Sources de données (santé)",
    categorie: "panneau",
    motsCles: [
      "data",
      "sources",
      "santé",
      "health",
      "observabilité",
      "diagnostic",
      "quota",
      "fraicheur",
      "erreur",
      "flux",
      "connexion",
      "statut",
    ],
    apercu: "Ouvre / ferme l'observabilité des sources (états, quotas, fraîcheur, erreurs)",
    action: basculer("data"),
  },
  {
    id: "panneau:dist",
    mnemonique: "DIST",
    libelle: "Distribution des rendements (VaR)",
    categorie: "panneau",
    motsCles: [
      "distribution",
      "dist",
      "var",
      "value at risk",
      "cvar",
      "expected shortfall",
      "quantile",
      "percentile",
      "rendements",
      "risque",
      "queue",
      "tail",
    ],
    apercu: "Ouvre / ferme la distribution empirique des rendements du chart en niveaux de prix (VaR/CVaR)",
    action: basculer("dist"),
  },
  {
    id: "panneau:expy",
    mnemonique: "EXPY",
    libelle: "Journal de trades",
    categorie: "panneau",
    motsCles: [
      "expy",
      "journal",
      "trades",
      "expectancy",
      "esperance",
      "r multiple",
      "risque",
      "win rate",
      "profit factor",
      "equity",
      "backtest manuel",
    ],
    apercu: "Ouvre / ferme le journal de trades (expectancy en R, équité, histogramme)",
    action: basculer("expy"),
  },
  {
    id: "panneau:paper",
    mnemonique: "PAPER",
    libelle: "Paper trading",
    categorie: "panneau",
    motsCles: [
      "paper",
      "papier",
      "simulation",
      "ordre",
      "ordres",
      "market",
      "limit",
      "stop",
      "tp",
      "sl",
      "position",
      "trading",
    ],
    apercu: "Ouvre / ferme le paper trading (ordres simulés, TP/SL, journalisation EXPY)",
    action: basculer("paper"),
  },
  {
    id: "panneau:mine",
    mnemonique: "MINE",
    libelle: "Coût de production (minage)",
    categorie: "panneau",
    motsCles: [
      "mine",
      "minage",
      "mining",
      "cout de production",
      "production cost",
      "hashprice",
      "hashrate",
      "difficulte",
      "difficulty",
      "electricite",
      "kwh",
      "plancher",
      "capriole",
    ],
    apercu: "Ouvre / ferme le coût de production du minage BTC (plancher électrique, all-in, hashprice)",
    action: basculer("mine"),
  },
  {
    id: "panneau:cycle",
    mnemonique: "CYCLE",
    libelle: "Cycle 4 ans (halving)",
    categorie: "panneau",
    motsCles: [
      "cycle",
      "halving",
      "4 ans",
      "four year",
      "bull",
      "bear",
      "top",
      "bottom",
      "drawdown",
      "mayer",
      "mvrv",
      "saison",
      "post-halving",
    ],
    apercu: "Ouvre / ferme la position dans le cycle de 4 ans BTC (4 cycles alignés jour-0, Mayer, MVRV)",
    action: basculer("cycle"),
  },
  {
    id: "panneau:evts",
    mnemonique: "EVTS",
    libelle: "Étude d'évènements",
    categorie: "panneau",
    motsCles: [
      "evts",
      "évènement",
      "evenement",
      "event study",
      "cpi",
      "nfp",
      "fomc",
      "macro",
      "alignement",
      "réaction",
    ],
    apercu: "Ouvre / ferme l'étude d'évènements (perf alignée autour des CPI/NFP/FOMC)",
    action: basculer("evts"),
  },
  {
    id: "panneau:scen",
    mnemonique: "SCEN",
    libelle: "Stress-test",
    categorie: "panneau",
    motsCles: [
      "stress",
      "stress-test",
      "scénario",
      "scenario",
      "choc",
      "chocs",
      "risque",
      "beta",
      "bêta",
      "var",
      "krach",
      "scen",
    ],
    apercu: "Ouvre / ferme le stress-test scénarios (sliders facteurs, P&L estimé, jauge VaR)",
    action: basculer("scen"),
  },
  {
    id: "panneau:cap",
    mnemonique: "CAP",
    libelle: "Capitalisation & dominance",
    categorie: "panneau",
    motsCles: [
      "capitalisation",
      "market cap",
      "mcap",
      "total",
      "total2",
      "total3",
      "dominance",
      "btc.d",
      "btcd",
      "eth.d",
      "altseason",
      "alts",
      "cap",
    ],
    apercu: "Ouvre / ferme TOTAL, TOTAL3 et les dominances (BTC, ETH, alts, top 100)",
    action: basculer("mcap"),
  },
  {
    id: "panneau:funding-matrix",
    mnemonique: "FUNDX",
    libelle: "Funding cross-exchange",
    categorie: "panneau",
    motsCles: [
      "funding",
      "cross-exchange",
      "cross exchange",
      "apr",
      "annualise",
      "perp",
      "binance",
      "bybit",
      "okx",
      "hyperliquid",
      "dex",
      "arbitrage",
      "fundx",
    ],
    apercu: "Ouvre / ferme la comparaison de funding perp (Binance/Bybit/OKX/Hyperliquid)",
    action: basculer("fundingMatrix"),
  },
  {
    id: "panneau:liquidations",
    mnemonique: "LIQ",
    libelle: "Liquidations",
    categorie: "panneau",
    motsCles: [
      "liquidations",
      "liquidation",
      "liq",
      "forceorder",
      "force order",
      "long liq",
      "short liq",
      "cascade",
      "squeeze",
      "perp",
      "binance",
    ],
    apercu: "Ouvre / ferme le flux de liquidations perp Binance (long/short)",
    action: basculer("liquidations"),
  },

  // ─── Gestion globale des fenêtres (agit sur toutes les fenêtres à la fois) ───
  {
    id: "panneau:wmin",
    mnemonique: "WMIN",
    libelle: "Réduire toutes les fenêtres",
    categorie: "panneau",
    motsCles: ["fenetres", "windows", "reduire", "minimiser", "minimize", "tout reduire", "wmin"],
    apercu: "Réduit d'un coup toutes les fenêtres ouvertes dans la barre de tâches",
    action: () => windowManagerStore.getState().minimizeAll(),
  },
  {
    id: "panneau:wall",
    mnemonique: "WALL",
    libelle: "Restaurer toutes les fenêtres",
    categorie: "panneau",
    motsCles: ["fenetres", "windows", "restaurer", "restore", "tout restaurer", "afficher", "wall"],
    apercu: "Restaure d'un coup toutes les fenêtres réduites",
    action: () => windowManagerStore.getState().restoreAll(),
  },
  {
    id: "panneau:wtile",
    mnemonique: "WTILE",
    libelle: "Mosaïque des fenêtres",
    categorie: "panneau",
    motsCles: ["fenetres", "windows", "mosaique", "tile", "grille", "tuiles", "disposer", "wtile"],
    apercu: "Dispose les fenêtres ouvertes en mosaïque plein écran",
    action: () => windowManagerStore.getState().tileOpenWindows(),
  },
  {
    id: "panneau:wcasc",
    mnemonique: "WCASC",
    libelle: "Cascade des fenêtres",
    categorie: "panneau",
    motsCles: ["fenetres", "windows", "cascade", "empiler", "escalier", "wcasc"],
    apercu: "Réempile les fenêtres ouvertes en cascade",
    action: () => windowManagerStore.getState().cascadeAll(),
  },
  {
    id: "panneau:wclose",
    mnemonique: "WCLOSE",
    libelle: "Fermer TOUTES les fenêtres",
    categorie: "panneau",
    motsCles: ["fenetres", "windows", "fermer", "close", "tout fermer", "fermer toutes", "wclose"],
    apercu: "Ferme d'un coup toutes les fenêtres ouvertes (géométrie conservée)",
    action: () => windowManagerStore.getState().closeAll(),
  },
];
